spring:
  datasource:
    #    url: ec2-3-217-113-25.compute-1.amazonaws.com
    #    url: jdbc:mysql://localhost:3306/jobfinderdb?createDatabaseIfNotExist=true
    url: jdbc:postgresql://ec2-3-217-113-25.compute-1.amazonaws.com:5432/de6eljg77hr001
    username: hfefeurrpbpjrc
    password: 4daa2e1c38716227cae1f47daba33cd3b421a28640e125c11c35bfb3739bb255
    driver-class-name: org.postgresql.Driver
  tomcat:
    max-active: 10
    max-idle: 5
    min-idle: 2
    remove-abandoned: true
    initial-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.H2Dialect
        #        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
  port: 8080 # This is the default port anyway, but you can change it here

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
